version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped

  book-service:
    build:
      context: ./BookService
      dockerfile: Dockerfile
    container_name: book-service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  recommendation-service:
    build:
      context: ./RecommendationService
      dockerfile: Dockerfile
    container_name: recommendation-service
    ports:
      - "8001:8001"
    restart: unless-stopped

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - MONGO_URL=${MONGO_URL_USER}
    depends_on:
      - mongo
    restart: unless-stopped

  loan-service:
    build:
      context: ./loan-service
      dockerfile: Dockerfile
    container_name: loan-service
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=production
      - MONGO_URL=${MONGO_URL_LOAN}
    depends_on:
      - mongo
    restart: unless-stopped
