version: "3.9"
services:
  loan-service:
    build: .
    ports:
      - "5002:5002"
    environment:
      PORT: 5002
      MONGO_URL: "mongodb+srv://eriklasic:ImRLKeb3s98fbGrF@cluster0.wtxui1k.mongodb.net/loanservice?retryWrites=true&w=majority"
      USER_SERVICE_URL: "http://localhost:5001/api"
      BOOK_SERVICE_URL: "http://localhost:8000"
      DISABLE_AUTH: "false"
    restart: unless-stopped
