version: "3.9"
services:
  user-service:
    build: .
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      MONGO_URL: "mongodb+srv://eriklasic:ImRLKeb3s98fbGrF@cluster0.wtxui1k.mongodb.net/userservice?retryWrites=true&w=majority"
      JWT_SECRET: "mysecretkey"
    restart: unless-stopped
